### PR TITLE
Added Passwordless.ID helper lib

### PR DESCRIPTION
**Pull request by dagnelies**

### CODE REVIEW

**Comment by herrjemand** [comment]
Nice tool, but this PR needs to be redone.

Only two mentions:

One: In the demos: Link to demo first, and then mention repo.

Two: In the server libs: Link to repo. No link to demo.

Others are not relevant to this implementation.

Otherwise looks useful *) Thx

**Comment by herrjemand** [comment]
Please update PR as requested. I am working on rewriting some sections and will add stuff as we go. For now your solution only qualifies for those two categories.

Thx

**Comment by dagnelies** [comment]
Whatever, here you go. Happy new year 🎉

**Comment by herrjemand** [comment]
Thanks @dagnelies. Frohes neues Jahr!

**Pull request merged**
