### PR TITLE
Add Wallix's JavaScript library for FIDO2

### PR DESCRIPTION
**Pull request by Kmaschta**
I used this small library to integrate FIDO2 authentication on the browser and a NodeJS API.

These libraries works in pair and make the integration of FIDO2 pretty quick!

### CODE REVIEW

**Comment by herrjemand** [comment]
Client library means: library that acts as client, like a browser. Please remove your library from the client and I will merge it.

**Comment by herrjemand** [comment]
@Kmaschta I think you've removed wrong thing. Keep the server and remove the client lib.

**Comment by Kmaschta** [comment]
Damn! My bad... I haven't drink my coffee at the time

**Comment by herrjemand** [comment]
Thx @Kmaschta

**Pull request merged**
