### PR TITLE
FIDO2 for ASP.NET

### PR DESCRIPTION
**Pull request by scottbrady91**
FIDO2 conformant implementation for ASP.NET Core.

Conformance

### CODE REVIEW

**Comment by herrjemand** [comment]
@scottbrady91 is it open source?

**Comment by herrjemand** [comment]
@scottbrady91 is it open source?

**Comment by scottbrady91** [comment]
It is not. Is that a requirement?

**Comment by herrjemand** [comment]
@scottbrady91 Welcome to the github *)

**Comment by herrjemand** [comment]
@scottbrady91 Yes. Pure commercial implementations are not the focus of this project.

If you want to be a member of a far more awesome club, you can always apply for FIDO2 certification https://fidoalliance.org/certification/, get certified and be listed in FIDO2 certified list with addition to be announced!

**Comment by scottbrady91** [comment]
No worries! If you're in South Korea in a couple of weeks, I'll see you there.

**Pull request closed without merging**
