### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by token2**
A demo page to test security keys sold by Token2 or any other vendor

### CODE REVIEW

**Review by token2 — COMMENTED** [review]
Typo fixed

**Comment by herrjemand** [comment]
@token2 is there a source code available on the github?

**Comment by token2** [comment]
> @token2 is there a source code available on the github?
No, not yet - this is just an online tool for tests

**Comment by herrjemand** [comment]
@token2 Unfortunately this project only hosts open source projects. Additionally I am starting to slowly squash all basic demos, because they ultimately do not bring anything new to the plate. 

If you guys decide to do kick-ass open source demo, then I will gladly add it to this project.

**Pull request closed without merging**
