### PR TITLE
Add OnlyKey to List

### PR DESCRIPTION
**Pull request by onlykey**

### CODE REVIEW

**Comment by herrjemand** [comment]
@onlykey Could you guys show me the logs of you passing the conformance tools, and link to the source code?

**Comment by onlykey** [comment]
@herrjemand Here are the logs of OnlyKey and logs of Solo to compare:

onlykey - https://docs.google.com/document/d/1cGth-2HMA5yUvUCWYoPbJtgPMiGiTP1K__hWW1R3MDM/edit?usp=sharing

solo - https://docs.google.com/document/d/1LNyCmhgfQAIKAA-NeLrba8iXTTBmpEAVDjxVxjHVPRo/edit?usp=sharing

We implemented some additional tweaks in our FIDO2 so that more of the tests pass.

Here is the firmware source:
https://github.com/trustcrypto/libraries
https://github.com/trustcrypto/OnlyKey-Firmware

**Comment by herrjemand** [comment]
@onlykey 
CTAP2_ERR_PIN_AUTH_BLOCKED(52)
    at sendCTAP_CBOR.then (eval at compileCode (js/sandbox.js:25:26), <anonymous>:2528:23)
    at <anonymous>


Can you pass tests and make screenshot?

**Comment by onlykey** [comment]
@herrjemand This is an issue with the solo library, you can see that solo key also has the same failure on that test- https://docs.google.com/document/d/1LNyCmhgfQAIKAA-NeLrba8iXTTBmpEAVDjxVxjHVPRo/edit?disco=AAAADeqsYt0

**Comment by onlykey** [comment]
@herrjemand I wanted to follow up here. Would you be able to accept the PR? It looks like OnlyKey is currently the most compliant of the 4 keys listed (U2F Zero is not FIDO2, Trezor is partially FIDO2 compliant, Solo is partially FIDO2 compliant - passes 114 tests, OnlyKey is partially FIDO2 compliant - passes 117 tests).

**Comment by herrjemand** [comment]
@onlykey U2F Zero is an important project and it passed conformance tests. Trezor and Solo both provided results, and Solo has official certification.

You guys need to provide me with passing all tests if you want to be called compliant.

**Comment by onlykey** [comment]
@herrjemand Can you share the results that Solo and Trezor provided? I would be interested to see how those results are different from my testing. I have ran the conformance tests on Solo multiple times and it only passes 114 tests (partially conformant), I will test Trezor too but from their documentation it indicated they were not fully conformant.

**Comment by herrjemand** [comment]
@onlykey https://medium.com/solokeyssec/solokeys-achieves-fido2-certification-thanks-to-mozilla-4c9ea52c05dd

**Comment by herrjemand** [comment]
@onlykey what tests are you failing?

**Comment by onlykey** [comment]
@herrjemand Yes, I understand that Solo is FIDO2 certified, and passed interop testing, but that does not necessary mean it passes all tests using this conformance tool. If you can share the results that Solo provided I can compare them to these results, which show multiple failures:

Solo fails these on these tests:

Fail 1
https://docs.google.com/document/d/1LNyCmhgfQAIKAA-NeLrba8iXTTBmpEAVDjxVxjHVPRo/edit?disco=AAAADu7yBkI

Fail 2
https://docs.google.com/document/d/1LNyCmhgfQAIKAA-NeLrba8iXTTBmpEAVDjxVxjHVPRo/edit?disco=AAAADu7yBkQ

Fail 3
https://docs.google.com/document/d/1LNyCmhgfQAIKAA-NeLrba8iXTTBmpEAVDjxVxjHVPRo/edit?disco=AAAADu7yBkU

Fail 4
https://docs.google.com/document/d/1LNyCmhgfQAIKAA-NeLrba8iXTTBmpEAVDjxVxjHVPRo/edit?disco=AAAADu7yBkY

Fail 5
https://docs.google.com/document/d/1LNyCmhgfQAIKAA-NeLrba8iXTTBmpEAVDjxVxjHVPRo/edit?disco=AAAADu7yBkc

Fail 6
https://docs.google.com/document/d/1LNyCmhgfQAIKAA-NeLrba8iXTTBmpEAVDjxVxjHVPRo/edit?disco=AAAADu7yBkg

Fail 7
https://docs.google.com/document/d/1LNyCmhgfQAIKAA-NeLrba8iXTTBmpEAVDjxVxjHVPRo/edit?disco=AAAADu7yBkE

Fail 8
https://docs.google.com/document/d/1LNyCmhgfQAIKAA-NeLrba8iXTTBmpEAVDjxVxjHVPRo/edit?disco=AAAADu7yBko

Fail 9
https://docs.google.com/document/d/1LNyCmhgfQAIKAA-NeLrba8iXTTBmpEAVDjxVxjHVPRo/edit?disco=AAAADu7yBkw

**Comment by herrjemand** [comment]
@onlykey Can I haz screenshots?

**Comment by onlykey** [comment]
@herrjemand I can do better than that you can haz video :)

I upgraded Solo to the latest 3.0 firmware and ran this test, on the FIDO Conformance Tools v1.1.0
https://drive.google.com/file/d/1EDlQczFOmFAcoj02bYcGDQU6Y_bY1c1_/view?usp=sharing

**Comment by herrjemand** [comment]
@onlykey Look guys. You obviously got wrong metadata, this is why solokeys are failing.

But in general you need to concentrate on your and not what others doing. As of now, you have not provided any information on what issues you are experiencing. And until you are provided me with the information about the issues, we resolve them, you pass "ALL" of the tests, then I am happy to mark you as compliant.

**Comment by onlykey** [comment]
@herrjemand I am not sure I understand this, can you explain what you mean about wrong metadata?

> But in general you need to concentrate on your and not what others doing

OnlyKey is literally using the open source Solo key library on different hardware, so we are doing the same thing. If Solo can pass "ALL" of the tests then so can OnlyKey, if Solo cannot and you have it marked as "COMPLIANT" then it's only fair to mark other solutions that meet or exceed the standard you have set for what qualifies as compliant.

Telling us that we have to pass "ALL" the tests when the other keys listed as complaint cannot is not fair. If as you mentioned:

> Trezor and Solo both provided results

Why not share these results to compare with the results I have shared?

**Comment by herrjemand** [comment]
@onlykey You guys need to update your metadata then, and change attestation root certificate.

**Comment by onlykey** [comment]
@herrjemand I am confused by your response, the test results I have provided are from the FIDO Certified Solo Key.

**Comment by herrjemand** [comment]
@onlykey You are not solokeys, right?

**Comment by onlykey** [comment]
@herrjemand We are using solo key's open source library so yes we essentially to the computer and to the conformance tools, are a solo key. So telling us to go fix our device is basically like saying, I don't care that solo key does not pass the conformance tools, you have to pass the conformance tools which is clearly unfair. 

> Trezor and Solo both provided results

If this is true then why not share these results to compare with the results I have shared?

**Comment by herrjemand** [comment]
@onlykey If you are simply a clone of the Solokey then what is the use of adding @onlykey 
to the list?

**Comment by onlykey** [comment]
@herrjemand FIDO2 is one of many features supported by OnlyKey - https://docs.crp.to/features.html 

I am not sure what else to say to you here, just do the right thing. Anyone who reads this can see that OnlyKey is more conformant to FIDO2 than solo key (At least from my testing which I shared above, tested with the FIDO2 conformance tools). If you won't add OnlyKey to the list because it doesn't pass "ALL TESTS" then you should remove solo key from your list because it passes even less tests.

**Comment by herrjemand** [comment]
@onlykey Here is my judgement:

1. You are simply using same source as Solokeys, and do not provide anything new to the community.

2. YOU! Not solokeys. You did not pass the conformance tests. Solokeys achieved official FIDO2 Certification which means that they passed both, the tools and have passed L1 security assessment.

3. You need to concentrate on the problem you are having, which is as I said, that you clearly did not set your metadata properly. You did not set your root certificate properly. Do some research. 

4. It's a show of a very bad manner to tell people what to do with their stuff and what not. You have come to the open source project, that I made for the community, that I maintain in my free time, outside of the two hundred plus hours of work, and manage to tell me what I should do with my project. I think you are far over your head and need to start respect people's time and effort to even read your pull requests.

You come here for pr, not to give something back to the community. 

Hence closed.

**Comment by onlykey** [comment]
Well at least you admit it...

>  tell people what to do with their stuff and what not

@herrjemand does what he wants with his stuff and it seems is only interested in listing projects he personally likes on this site, if you are looking for things that are actually FIDO2 compliant look elsewhere.

**Comment by herrjemand** [comment]
@onlykey You are free to fork and do your own stuff

**Comment by herrjemand** [comment]
If you are reading this, this means that you found this issue based on the google searching for 

79d699df-0191–4b10-b903–5467e7ce8231

This AAGUID is assigned to the FIDO Alliance FIDO2 Testing Virtual Authenticator.

OnlyKey has taken a test metadata, and used it as their own without modifying it.

The company who you can meet by reading comments above did not pass the conformance tests, nor certified.

Based on the fact that they used test metadata without modification you can deduct that their product is questionable at best.

Buy certified security keys.

Feitian: https://www.amazon.com/s?k=feitian+fido2

Trustkey: https://www.amazon.com/s?k=trustkey+fido2

Yubikey: https://www.yubico.com/store/

Thetis: https://www.amazon.com/s?k=thetis+fido+certified

GoTrust: https://www.amazon.com/s?k=Gotrust+fido

**Pull request closed without merging**
